### PR TITLE
handle CF$UID objects

### PR DESCRIPTION
**Pull request by davvidbaker**
When trying to use this library, my plist wouldn't parse. Digging in, I found `Plist.Binary.read_object/3` was missing a case for the `0x08` type, which [I guess is uncommon](http://plist.sourceforge.net/lib/doc/2.1.0a/net/sf/plist/NSUID.html).

This change should handle it appropriately.

Thanks for the great library 👍!

### CODE REVIEW

**Comment by ciaran** [comment]
Thanks for the patch, if we’re adding handling for a new type it needs to be in the tests though.

Could you add your sample to the test files?

**Comment by davvidbaker** [comment]
Just added tests for xml and binary! 

The UID stuff won't show up in XCode's plist viewer, but you can confirm that `0x08` type is indeed the case if you add an `IO.puts` in that function and run the tests.

**Comment by ciaran** [comment]
It’s really hard to see what the right way to handle this is given the limited information available, so we may need to make a breaking change here in the future, but for now I’ve gone ahead and merged it.

Thanks!

**Comment by davvidbaker** [comment]
Yeah totally. Thanks again!

**Pull request merged**
